// Every photo and video from the night. Files are generated by scripts/process-media.mjs
// from the raw phone media in ./media; this file adds tags and captions on top.

import raw from './media.json'

export type Tag = 'track' | 'carnage' | 'wave' | 'podium' | 'paddock' | 'screen' | 'overview'

export interface MediaItem {
  id: string
  kind: 'photo' | 'video'
  src: string
  thumb: string
  w: number
  h: number
  duration?: number
  tags: Tag[]
  caption: string
}

const CURATED: Record<string, [Tag[], string]> = {
  m001: [['paddock'], 'The grid. Fifteen suits, one helmet.'],
  m002: [['paddock'], 'Photobomb of the night. We are all a little scared.'],
  m003: [['paddock'], 'Helmet hair, adrenaline, excuses already loading.'],
  m004: [['podium'], 'Pure, unfiltered joy. Deserved.'],
  m005: [['podium'], 'Top three, trophies in hand.'],
  m006: [['podium'], 'The pose. Practised? Absolutely.'],
  m007: [['podium'], 'Flex on the steps.'],
  m008: [['podium'], 'Take two. Same grins.'],
  m009: [['track'], 'Eyes up, elbows in, foot flat.'],
  m013: [['track', 'overview'], 'The whole circus from the balcony.'],
  m018: [['carnage'], 'Karts that are definitely not meant to be touching.'],
  m022: [['carnage'], 'A tangle, a marshal, and another red flag incoming.'],
  m023: [['screen'], 'The timing screen: where the truth lives.'],
  m025: [['carnage'], 'Marshal to the rescue. Again.'],
  m029: [['carnage'], 'Parked facing the tyre wall. Bold choice.'],
  m030: [['carnage'], 'Tyre wall 1, kart 0.'],
  m032: [['track', 'overview'], 'The serpentine, from above.'],
  m016: [['wave'], 'Waving mid-race. Race control has noted this.'],
  m033: [['wave'], 'A wave for the camera. Hands on the wheel, please.'],
  m039: [['wave'], 'Another wave. It became a thing.'],
  m044: [['wave'], 'Is this a race or a parade?'],
  m047: [['carnage'], 'The orange hi-vis crew earned their money tonight.'],
  m049: [['carnage'], 'Tyre-wall extraction, part three.'],
  m051: [['carnage'], 'Pit crew, but make it a rescue mission.'],
  m058: [['screen'], 'Lap times loading… and loading…'],
  m064: [['track'], 'Close enough to smell the brakes.'],
  m066: [['track', 'overview'], 'Spot the kart that’s about to cause a red flag.'],
  m068: [['carnage'], 'Contact. Race control is typing…'],
  m073: [['track'], 'Number 11, fully committed.'],
  m075: [['wave'], 'Still waving. Still racing. Somehow.'],
  m078: [['wave'], 'The wave count is getting out of hand.'],
  m089: [['screen'], 'Leaderboard check between red flags.'],
  m096: [['track'], 'Tucked in and sending it.'],
  m097: [['carnage'], 'Marshal meeting in the tyre wall.'],
  m020: [['track'], 'Blink and you miss it.'],
  m026: [['track', 'overview'], 'The view from the pit lane.'],
  m028: [['track'], 'Full send past the camera.'],
  m076: [['track'], 'Motion blur is a personality.'],
  m099: [['track', 'overview'], 'The whole track, in all its glory.'],
  m103: [['carnage'], 'Live from the tyre wall: a rescue in real time.'],
  m104: [['track', 'overview'], 'Fifteen karts, one track, zero patience.'],
  m105: [['track', 'overview'], 'Overhead chaos, bridge and all.'],
  m107: [['track', 'overview'], 'Pit lane view of the whole circus.'],
}

const TRACK_LINES = [
  'Racing line: optional.',
  'Apex? Never heard of her.',
  'Somewhere in here is a black flag waiting to happen.',
  'The hairpin claims another victim.',
  'Late on the brakes, early on the excuses.',
  'Nose to tail through the kerbs.',
  'A rare moment of green-flag racing.',
  'Formation flying, karting edition.',
  'Traffic, TeamSport style.',
  'Tyre wall getting nervous.',
  'Is that a gap? It’s a gap if you believe.',
  'Concentration face: engaged.',
]

export const MEDIA: MediaItem[] = (raw as Omit<MediaItem, 'tags' | 'caption'>[]).map((m, i) => {
  const c = CURATED[m.id]
  return { ...m, tags: c?.[0] ?? ['track'], caption: c?.[1] ?? TRACK_LINES[i % TRACK_LINES.length] }
})

export const byId = (id: string) => MEDIA.find((m) => m.id === id)!
export const PHOTOS = MEDIA.filter((m) => m.kind === 'photo')
export const VIDEOS = MEDIA.filter((m) => m.kind === 'video')
export const withTag = (t: Tag) => MEDIA.filter((m) => m.tags.includes(t))

export const HERO_VIDEO = byId('m104')
export const SQUAD = byId('m001')
export const PODIUM_SET = ['m007', 'm006', 'm005', 'm004', 'm008'].map(byId)
export const CARNAGE = withTag('carnage')
